### ISSUE TITLE
Reload required to start new test.

### ISSUE THREAD

**Issue by eshaan007** [Kelta-King/Typing_test#1]
In this test, there is no chance of getting the result if the page is not reloaded.

**Comment by Kelta-King** [comment]
Now re-check it and do let me know if an error occurs...

**Comment by eshaan007** [comment]
Ye sit is fixed. Good work bro!

**Comment by Kelta-King** [comment]
Thanks, bro for reviewing it

**Comment by eshaan007** [comment]
Anytime! Will let you know if any others are present!
